<center>
<object
  classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
  codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,22,0"
  id="armiks"
  width="468" height="60">
  <param name="movie" value="http://armiks.ru/flash/armiks.swf" >
  <param name="bgcolor" value="#FFFFFF" >
  <param name="quality" value="high" >
  <param name="allowscriptaccess" value="samedomain" >
  <embed
    type="application/x-shockwave-flash"
    pluginspage="http://www.macromedia.com/go/getflashplayer"
    name="armiks"
    width="468" height="60"
    src="armiks.swf"
    bgcolor="#FFFFFF"
    quality="high"
    swliveconnect="true"
    allowscriptaccess="samedomain">
    <noembed>
    	<a href="http://armiks.ru">http://armiks.ru</a>	
    </noembed>
  </embed>
</object>
</center>