
<TABLE border="0" cellPadding="4" cellSpacing="0" align="center">
 <TR>
	<TD align="center">	
		<a href="http://www.yandex.ru/cy?base=0&host=www.armiks.ru"> 
			<img src="http://www.yandex.ru/cycounter?www.armiks.ru" width="88" height="31" 
			alt="Яндекс цитирования" border="0"> 
		</a> 
 	
	</td>
 	<TD align="center">
 			<!--begin of Top100 logo-->
			<a href="http://top100.rambler.ru/top100/">
			<img src="http://top100-images.rambler.ru/top100/banner-88x31-rambler-gray2.gif" alt="Rambler's Top100" width="88" height="31" border="0"></a>
			<!--end of Top100 logo -->
 	</td>
  <TD align="center">
			<!-- HotLog -->

			<script type="text/javascript" language="javascript">
			hotlog_js="1.0";
			hotlog_r=""+Math.random()+"&s=337305&im=134&r="+escape(document.referrer)+"&pg="+
			escape(window.location.href);
			document.cookie="hotlog=1; path=/"; hotlog_r+="&c="+(document.cookie?"Y":"N");
			</script>
			<script type="text/javascript" language="javascript1.1">
			hotlog_js="1.1";hotlog_r+="&j="+(navigator.javaEnabled()?"Y":"N")
			</script>
			<script type="text/javascript" language="javascript1.2">
			hotlog_js="1.2";
			hotlog_r+="&wh="+screen.width+'x'+screen.height+"&px="+
			(((navigator.appName.substring(0,3)=="Mic"))?
			screen.colorDepth:screen.pixelDepth)</script>
			<script type="text/javascript" language="javascript1.3">hotlog_js="1.3"</script>
			<script type="text/javascript" language="javascript">hotlog_r+="&js="+hotlog_js;
			document.write("<a href='http://click.hotlog.ru/?337305' target='_top'><img "+
			" src='http://hit15.hotlog.ru/cgi-bin/hotlog/count?"+
			hotlog_r+"&' border=0 width=88 height=31 alt=HotLog><\/a>")
			</script>
			<noscript>
			<a href="http://click.hotlog.ru/?337305" target="_top"><img src="http://hit15.hotlog.ru/cgi-bin/hotlog/count?s=337305&amp;im=134" border=0 
			 width=88 height=31 alt="HotLog"></a>
			</noscript>
			
			<!-- /HotLog -->
	</TD>
	<td>
		<a href="http://stat.aport.ru/hit.pl?id=1760972"><img src="http://stat.aport.ru/show.pl?tp=26&id=1760972" height=31 width=88 border=0 alt="Находится в каталоге Апорт"></a>
	</td>
	<TD align="center">
		<!--Rating@Mail.ru LOGO--><a target=_top
		href="http://top.mail.ru/jump?from=1024049"><img
		SRC="http://d0.ca.bf.a0.top.list.ru/counter?id=1024049;t=49;l=1"
		border=0 height=31 width=88
		alt="Рейтинг@Mail.ru"/></a><!--/LOGO-->
	</td>
	<TD align="center">
			<!--LiveInternet logo--><a href="http://www.liveinternet.ru/click" target=_blank><img
			src="http://counter.yadro.ru/logo?44.3" border=0
			title="LiveInternet" alt=""
			width=31 height=31></a><!--/LiveInternet-->
	</td>
	<TD align="center">
			<SCRIPT type="text/javascript">
			<!--
			Nnv=navigator;Nna=Nnv.appName;Nd=document;Nd.cookie="b=b";Nc=0;if(Nd.cookie)Nc=1;
			Nn=(Nna.substring(0,2)=="Mi")?0:1;Ns=screen;Npx=(Nn==0)?Ns.colorDepth:Ns.pixelDepth;
			str='<img src="http://c.ile.ru/61;'+Ns.width+'x'+Ns.height+';'+Npx+';'+Nc+';';
			str=str+escape(Nd.referrer)+';'+Math.random()+'" width="88" height="31" border="0">';
			document.write("<a href=http://www.ile.ru/ target=_top>"+str+"</a>");
			// -->
			</SCRIPT>
			<NOSCRIPT><a href=http://www.ile.ru/ target=_top><img src="http://c.ile.ru/61;0x0;0;0;-;0" width="88" height="31" border="0"></a></NOSCRIPT> 
 	</td>
</TR>
</TABLE>