<center>
<!--begin of Rambler's Top100 code -->
<a href="http://top100.rambler.ru/top100/">
    <img src="http://counter.rambler.ru/top100.cnt?854874" alt="" width="1" height="1" border="0">
</a>
<!--end of Top100 code-->

<!--LiveInternet counter-->
    <script type="text/javascript"><!--document.write('<img src="http://counter.yadro.ru/hit?r'+
            escape(document.referrer)+((typeof(screen)=='undefined')?'':
            ';s'+screen.width+'*'+screen.height+'*'+(screen.colorDepth?
                screen.colorDepth:screen.pixelDepth))+';u'+escape(document.URL)+
            ';'+Math.random()+ '" width=1 height=1 alt="">')//-->
    </script>
<!--/LiveInternet-->

<!--Rating@Mail.ru COUNTER-->
    <script language="JavaScript" type="text/javascript">
        <!-- d=document;var a='';a+=';r='+escape(d.referrer) js=10//-->
    </script>
    <script language="JavaScript1.1" type="text/javascript">
        <!--a+=';j='+navigator.javaEnabled() js=11//-->
    </script>
    <script language="JavaScript1.2" type="text/javascript">
        <!-- s=screen;a+=';s='+s.width+'*'+s.height a+=';d='+(s.colorDepth?s.colorDepth:s.pixelDepth)
        js=12//-->
    </script>
    <script language="JavaScript1.3" type="text/javascript">
        <!--js=13//-->
    </script>
    <script language="JavaScript" type="text/javascript">
        <!--d.write('<IMG src="http://d0.ca.bf.a0.top.list.ru/counter?id=1024049;js='+js+a+
        ';rand='+Math.random()+'height=1 width=1/>') if(11<js)d.write('<'+'!-- ')//-->
    </script>
    <noscript>
        <img src="http://d0.ca.bf.a0.top.list.ru/counter?js=na;id=1024049" height="1" width="1" alt=""/>
    </noscript>
    <script language="JavaScript" type="text/javascript">
        <!--if(11<js)d.write('--'+'>')//-->
    </script>
    <!--/COUNTER-->

</center>