<center>
		
	<script type="text/javascript" src="http://infobox.ru/ob.php?b=0&ref=9006"></script>
	<br><br>
		
	<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
            codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0"
            WIDTH=88 HEIGHT=31>
	    <PARAM NAME=movie VALUE="http://pics.rbc.ru/informer/flash/meteo.swf?MU=27612">
        <PARAM NAME=quality VALUE=high>
        <param name=MU value=27612>
        <PARAM NAME=bgcolor VALUE=#FFFFFF>
        <EMBED src="http://pics.rbc.ru/informer/flash/meteo.swf?MU=27612" quality=high
               bgcolor=#FFFFFF  WIDTH=88 HEIGHT=31 TYPE="application/x-shockwave-flash"
               PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">
        </EMBED>
	</OBJECT>	
	<br><br>
	
	<script>
	    document.write( '<a href="http://www.informer.ru/cgi-bin/redirect.cgi?id=177_1_1_45_40_1-0&url=http://www.rbc.ru&src_url=usd/eur_cb_forex_127815_88x90.gif" target="_blank"><img src="http://pics.rbc.ru/img/grinf/usd/eur_cb_forex_127815_88x90.gif?'+ Math.floor( 100000*Math.random() ) + '" WIDTH=88 HEIGHT="90" border=0></a>');
	</script>
	<br><br>
	
</center>	