<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html> 

<head>
	<title>&quot;Армикс-2000&quot; &#151; теплотехническое оборудование, котельное оборудование, котлы, вентиляторы и отопительное оборудование, металлоконструкции.</title>
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
	<meta name="keywords" content="ООО, АРМИКС-2000, производство, нагреватель, вода, теплотехническое, оборудование, жилищный, промышленный, социально-культурный, объект, традиционный, стандартный, водоподогреватель, высоко, эффективный, блочный, тип, база, изготовление, ЦТП, ИТП, нового, поколения, типовое, оборудование, выполняет, проект, индивидуальный, заказ, заказчик, специалист, завод, тепло, водонагреватель, производить, холод, нагрев, проектирование, монтаж, наладка, пуск, эксплуатация, система, отопление, горячее, холодное, водоснабжение, гарантия, комплекс, работа, сотрудничество, организация.">  
	<meta name="description" content="ООО АРМИКС-2000 продает теплотехническое оборудование для жилищных, промышленных, социально-культурных объектов, включающее традиционные водоподогреватели и новый высокоэффективный водоподогреватель блочного типа, на базе которого изготавливаются ЦТП и ИТП нового поколения. Кроме того, АРМИКС-2000 не ограничивается изготовлением типового оборудования и выполняет индивидуальные заказы.">  
	<meta name="author" content="Andrey N. Petkevich">
	<meta http-equiv="Pragma" content="no-cache">
	<link href="style.css" rel="stylesheet" type="text/css">
</head>


<body background="pics/background.gif">

	<table width="100%" cellpadding="0" cellspacing="0"
		style="border-bottom-style:dotted;border-bottom-width:1px;border-bottom-color:black">
		<tr>
			<td bgcolor="#CC99FF" width="150"><img style="border:0;width:150px;height:140px;" src="pics/logo.jpg" alt="Лого"></td>
			
			<td bgcolor="#CC99FF"  width="1" background="pics/tabl_border2.gif"></td>
			
	    <td valign="middle">
			<td bgcolor="#CC99FF" class="text_neo">
				<table border="0" width="100%" cellpadding="0" cellspacing="0">
					<tr>
						<td>
<!----------Здесь начинается текст счетчиков (невидимые - 1х1)-------------------------------------->
	      <? include ('config/count_head.inc'); ?>
<!----------Конец текста счетчиков (невидимые - 1х1)------------------------------------------------>
<!----------Здесь начинается текст БАННЕРОВ--------------------------------------------------------->	      	
	      <? include ('config/banners_head.inc'); ?>	
<!----------Конец текста счетчиков БАННЕРОВ--------------------------------------------------------->
						</td>						
					</tr>
					<tr>
						<td  class="text_neo">
							<div align="center">
								<br>
								<span style="font-size: 9pt;">Общество с ограниченной ответственностью</span><br>
								<span style="font-size: 20pt;">АРМИКС-2000</span>
							</div>
						</td>
					</tr>
			</table>
			</td>
			<td bgcolor="#CC99FF" width="1" background="pics/tabl_border2.gif"> </td>
			<td bgcolor="#CC99FF" width="5">&nbsp</td>
			<td bgcolor="#CC99FF" width="150">
					<table cellspacing=0 cellpadding=0 width="150" border=0>
	        	<tr><td><img height=1 src="pics/spacer.gif" width=1 alt="spacer"></td></tr>
	        	<tr> 
	          	<td class="TD1"> 
								<table cellspacing=2 cellpadding=2 width="100%" border=0 class="TD6" >
	             		<tr><td><div align="center" class="head_news">Наши координаты</div></td></tr>
	              </table>
							</td>
	        	</tr>
	        	<tr> 
	          	<td bgcolor="#000000"><img height=1 src="pics/spacer.gif" width=1 alt="spacer"></td>
	        	</tr>
	        	<tr> 
	          	<td class=TD2> 
	            	<table cellspacing=5 cellpadding=5 width="100%" border=0 >
	              	<tr> 
	                	<td valign=top> 
	                  	<div align="center" class="text_news">тел.: (495) 768-03-89<br>
	                  		тел/факс:<br>(495)926-76-50<br>
	            					<a href="mailto:info&#64;armiks.ru?subject=from_web_page">info&#64;armiks.ru</a><br>  
		  									<a href="http://armiks.ru">http://armiks.ru</a>	
	                  	</div>
	                	</td>
	              	</tr>
	              </table>
	            </td>
	        	</tr>
	      </table>			
			</td>	
			<td bgcolor="#CC99FF" width="5">&nbsp</td>
			<td bgcolor="#CC99FF"  width="1" background="pics/tabl_border2.gif"> </td>
		</tr>
	</table>
	          
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
	  <tr> 
	    <td  bgcolor="#99CC99" width="150" valign="top">
<!--------------Здесь начинается текст меню и баннеров----------------------------------------------->
	      <? include ('config/menu_side.inc'); ?>
<!--------------Конец текст меню и баннеров--------- ------------------------------------------------>    		
	    </td>
	    <td width="1" background="pics/tabl_border2.gif"></td>
	    <td valign="top"> 
	      <table width="100%" border="0" cellspacing="0" cellpadding="0">
	        <tr> 
	          <td width="10%">&nbsp;</td>
	          <td width="80%"> 
	          	<br>
<!--------------Здесь начинается текст блоков-------------------------------------------------------->
