	<br><br>
	<table width="95%" cellpadding="0" cellspacing="0">
  	<tr>
  		<td>
  			&nbsp
  		</td>
  		<td>
  			<img src="../pics/sp.gif" width="4" height="6" hspace="3" align="middle" alt="">
  		</td>
    	<td  class="text_menu">
				<a href="?topic=index">О компании</a>
    	</td>
  	</tr>
	</table>
	<br>
	
	<table width="95%" cellpadding="0" cellspacing="0">
  	<tr>
  		<td>
  			&nbsp
  		</td>
  		<td>
  			<img src="../pics/sp.gif" width="4" height="6" hspace="3" align="middle" alt="">
  		</td>
    	<td  class="text_menu">
			<a href="?topic=price">Прайс-лист</a>
    	</td>
  	</tr>
	</table>
	<br>	
	
	<table width="95%" cellpadding="0" cellspacing="0">
  	<tr>
  		<td>
  			&nbsp
  		</td>
  		<td>
  			<img src="../pics/sp.gif" width="4" height="6" hspace="3" align="middle" alt="">
  		</td>
    	<td  class="text_menu">
				<a href="?topic=dev01">Теплотехническое оборудование</a>
    	</td>
  	</tr>
	</table>
	<br>	
	
	<table width="95%" cellpadding="0" cellspacing="0">
  	<tr>
  		<td>
  			&nbsp
  		</td>
  		<td>
  			<img src="../pics/sp.gif" width="4" height="6" hspace="3" align="middle" alt="">
  		</td>
    	<td  class="text_menu">
				<a href="?topic=dev02">Котельное оборудование</a>
    	</td>
  	</tr>
	</table>
	<br>

    <table width="95%" cellpadding="0" cellspacing="0">
        <tr>
            <td>
                &nbsp
            </td>
            <td>
                <img src="../pics/sp.gif" width="4" height="6" hspace="3" align="middle" alt="">
            </td>
            <td  class="text_menu">
                <a href="?topic=dev05">Трубы экономайзерные</a>
            </td>
        </tr>
    </table>
    <br>

    <table width="95%" cellpadding="0" cellspacing="0">
  	<tr>
  		<td>
  			&nbsp
  		</td>
  		<td>
  			<img src="../pics/sp.gif" width="4" height="6" hspace="3" align="middle" alt="">
  		</td>
    	<td  class="text_menu">
				<a href="?topic=dev03">Котлы паровые</a>
    	</td>
  	</tr>
	</table>
	<br>	
	
	<table width="95%" cellpadding="0" cellspacing="0">
  	<tr>
  		<td>
  			&nbsp
  		</td>
  		<td>
  			<img src="../pics/sp.gif" width="4" height="6" hspace="3" align="middle" alt="">
  		</td>
    	<td  class="text_menu">
				<a href="?topic=dev04">Вентиляторы и отопительное оборудование</a>
    	</td>
  	</tr>
	</table>
	<br>	
	
	<table width="95%" cellpadding="0" cellspacing="0">
  	<tr>
  		<td>
  			&nbsp
  		</td>
  		<td>
  			<img src="../pics/sp.gif" width="4" height="6" hspace="3" align="middle" alt="">
  		</td>
    	<td  class="text_menu">
				<a href="?topic=contact_us">Координаты</a>
    	</td>
  	</tr>
	</table>
	<br>
	<table  width="100%" cellpadding="0" cellspacing="0" border="0"
		style="border-top-style:dotted;border-top-width:1px;border-top-color:black">
		<tr>
			<td align="center">
				<br>
				<br>
				<img src="../pics/reclama_2.jpg" width="94" height="25" align="middle" alt="Реклама">
				<br>
				<br>
			</td>
		</tr>
		<tr>
			<td>
<!--------------------Здесь начинаются банеры------------------------------------------------------->
      <? include ('config/hcntrs.inc'); ?>
<!--------------------Конец текста банеров   ------------------------------------------------------->
				<br>
			</td>
		</tr>
	</table>