<table  align=center border=0 cellpadding=0 cellspacing=0 width="100%">  
	<tbody>  
	<tr align=center>  
		<td class="text_menu">
			<img src="../pics/dots.jpg" width="8" height="8" hspace="3" align="middle" alt="">
			<a href="?topic=index">О компании</a>
		</td>  
		<td class="text_menu">
			<img src="../pics/dots.jpg" width="8" height="8" hspace="3" align="middle" alt="">
			<a href="?topic=price">Прайс-лист</a>
		</td>  
		<td class="text_menu">
			<img src="../pics/dots.jpg" width="8" height="8" hspace="3" align="middle" alt="">
			<a href="?topic=dev01">Теплотехническое<br>оборудование</a>
		</td>  
		<td class="text_menu">
			<img src="../pics/dots.jpg" width="8" height="8" hspace="3" align="middle" alt="">
			<a href="?topic=dev02">Котельное<br>оборудование</a>
		</td>
        <td class="text_menu">
            <img src="../pics/dots.jpg" width="8" height="8" hspace="3" align="middle" alt="">
            <a href="?topic=dev05">Трубы<br>экономайзерные</a>
        </td>
        <td class="text_menu">
			<img src="../pics/dots.jpg" width="8" height="8" hspace="3" align="middle" alt="">
			<a href="?topic=dev03">Котлы паровые</a>
		</td>  
	</tr>  
	</tbody> 
</table> 
